### ISSUE TITLE
Debugging failed invocations is difficult

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/rs-soroban-env#395]
Debugging failed invocations is difficult. When I invoke a function on a contract that doesn't exist in a Rust test, this is the output I see, which doesn't really elude to what's happened.

```
---- test::test stdout ----
thread 'test::test' panicked at 'called `Result::unwrap()` on an `Err` value: HostError
Value: Status(VmError(Function))

Debug events (newest first):
   0: "Function"

Backtrace (newest first):
   0: backtrace::backtrace::libunwind::trace
             at /Users/leighmcculloch/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.66/src/backtrace/libunwind.rs:93:5
      backtrace::backtrace::trace_unsynchronized
             at /Users/leighmcculloch/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.66/src/backtrace/mod.rs:66:5
   1: backtrace::backtrace::trace
             at /Users/leighmcculloch/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.66/src/backtrace/mod.rs:53:14
   2: backtrace::capture::Backtrace::create
             at /Users/leighmcculloch/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.66/src/capture.rs:176:9
   3: backtrace::capture::Backtrace::new_unresolved
             at /Users/leighmcculloch/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.66/src/capture.rs:170:9
   4: <soroban_env_host::host::error::HostError as core::convert::From<T>>::from
             at /Users/leighmcculloch/.cargo/git/checkouts/rs-soroban-env-230c62c6b1f3d3f1/0e6cb7a/soroban-env-host/src/host/error.rs:113:25
   5: <T as core::convert::Into<U>>::into
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/convert/mod.rs:550:9
   6: soroban_env_host::host::err_helper::<impl soroban_env_host::host::Host>::err
             at /Users/leighmcculloch/.cargo/git/checkouts/rs-soroban-env-230c62c6b1f3d3f1/0e6cb7a/soroban-env-host/src/host/err_helper.rs:18:37
   7: soroban_env_host::host::err_helper::<impl soroban_env_host::host::Host>::map_err::{{closure}}
             at /Users/leighmcculloch/.cargo/git/checkouts/rs-soroban-env-230c62c6b1f3d3f1/0e6cb7a/soroban-env-host/src/host/err_helper.rs:80:25
   8: core::result::Result<T,E>::map_err
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/result.rs:855:27
   9: soroban_env_host::host::err_helper::<impl soroban_env_host::host::Host>::map_err
             at /Users/leighmcculloch/.cargo/git/checkouts/rs-soroban-env-230c62c6b1f3d3f1/0e6cb7a/soroban-env-host/src/host/err_helper.rs:80:9
  10: soroban_env_host::vm::Vm::invoke_function_raw::{{closure}}
             at /Users/leighmcculloch/.cargo/git/checkouts/rs-soroban-env-230c62c6b1f3d3f1/0e6cb7a/soroban-env-host/src/vm.rs:295:28
  11: soroban_env_host::host::Host::with_frame
             at /Users/leighmcculloch/.cargo/git/checkouts/rs-soroban-env-230c62c6b1f3d3f1/0e6cb7a/soroban-env-host/src/host.rs:341:19
  12: soroban_env_host::vm::Vm::invoke_function_raw
             at /Users/leighmcculloch/.cargo/git/checkouts/rs-soroban-env-230c62c6b1f3d3f1/0e6cb7a/soroban-env-host/src/vm.rs:277:9
  13: soroban_env_host::host::Host::call_contract_fn
             at /Users/leighmcculloch/.cargo/git/checkouts/rs-soroban-env-230c62c6b1f3d3f1/0e6cb7a/soroban-env-host/src/host.rs:665:17
  14: soroban_env_host::host::Host::call_n
             at /Users/leighmcculloch/.cargo/git/checkouts/rs-soroban-env-230c62c6b1f3d3f1/0e6cb7a/soroban-env-host/src/host.rs:699:16
  15: <soroban_env_host::host::Host as soroban_env_common::checked_env::CheckedEnv>::call
             at /Users/leighmcculloch/.cargo/git/checkouts/rs-soroban-env-230c62c6b1f3d3f1/0e6cb7a/soroban-env-host/src/host.rs:1420:9
  16: soroban_env_common::checked_env::<impl soroban_env_common::env::Env for T>::call
             at /Users/leighmcculloch/.cargo/git/checkouts/rs-soroban-env-230c62c6b1f3d3f1/0e6cb7a/soroban-env-common/src/checked_env.rs:123:35
  17: <soroban_sdk::env::Env as soroban_env_common::env::Env>::call
             at /Users/leighmcculloch/.cargo/git/checkouts/rs-soroban-sdk-0ab58a716c671239/5dc9021/soroban-sdk/src/env.rs:496:13
  18: soroban_sdk::env::Env::invoke_contract
             at /Users/leighmcculloch/.cargo/git/checkouts/rs-soroban-sdk-0ab58a716c671239/5dc9021/soroban-sdk/src/env.rs:101:18
  19: soroban_cross_contract_b_contract::ContractB::add_with
             at src/lib.rs:10:9
  20: add_with
             at src/lib.rs:7:1
  21: soroban_cross_contract_b_contract::__add_with::invoke_raw_slice
             at src/lib.rs:7:1
  22: <soroban_cross_contract_b_contract::ContractB as soroban_sdk::testutils::ContractFunctionSet>::call
             at src/lib.rs:7:1
  23: <soroban_sdk::env::Env::register_contract::InternalContractFunctionSet<T> as soroban_env_host::host::ContractFunctionSet>::call
             at /Users/leighmcculloch/.cargo/git/checkouts/rs-soroban-sdk-0ab58a716c671239/5dc9021/soroban-sdk/src/env.rs:299:17
  24: soroban_env_host::host::Host::call_n::{{closure}}
             at /Users/leighmcculloch/.cargo/git/checkouts/rs-soroban-env-230c62c6b1f3d3f1/0e6cb7a/soroban-env-host/src/host.rs:693:21
  25: soroban_env_host::host::Host::with_frame
             at /Users/leighmcculloch/.cargo/git/checkouts/rs-soroban-env-230c62c6b1f3d3f1/0e6cb7a/soroban-env-host/src/host.rs:341:19
  26: soroban_env_host::host::Host::call_n
             at /Users/leighmcculloch/.cargo/git/checkouts/rs-soroban-env-230c62c6b1f3d3f1/0e6cb7a/soroban-env-host/src/host.rs:692:24
  27: <soroban_env_host::host::Host as soroban_env_common::checked_env::CheckedEnv>::call
             at /Users/leighmcculloch/.cargo/git/checkouts/rs-soroban-env-230c62c6b1f3d3f1/0e6cb7a/soroban-env-host/src/host.rs:1420:9
  28: soroban_env_common::checked_env::<impl soroban_env_common::env::Env for T>::call
             at /Users/leighmcculloch/.cargo/git/checkouts/rs-soroban-env-230c62c6b1f3d3f1/0e6cb7a/soroban-env-common/src/checked_env.rs:123:35
  29: <soroban_sdk::env::Env as soroban_env_common::env::Env>::call
             at /Users/leighmcculloch/.cargo/git/checkouts/rs-soroban-sdk-0ab58a716c671239/5dc9021/soroban-sdk/src/env.rs:496:13
  30: soroban_sdk::env::Env::invoke_contract
             at /Users/leighmcculloch/.cargo/git/checkouts/rs-soroban-sdk-0ab58a716c671239/5dc9021/soroban-sdk/src/env.rs:101:18
  31: soroban_cross_contract_b_contract::ContractBClient::add_with
             at src/lib.rs:7:1
  32: soroban_cross_contract_b_contract::test::test
             at src/test.rs:23:15
  33: soroban_cross_contract_b_contract::test::test::{{closure}}
             at src/test.rs:13:1
  34: core::ops::function::FnOnce::call_once
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/ops/function.rs:248:5

', /Users/leighmcculloch/.cargo/git/checkouts/rs-soroban-env-230c62c6b1f3d3f1/0e6cb7a/soroban-env-common/src/checked_env.rs:182:1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by graydon** [comment]
it now fails like so:

```
---- test::test stdout ----
thread 'test::test' panicked at 'HostError
Value: Status(VmError(TrapUnreachable))

Debug events (newest first):
   0: "escalating error 'Status(VmError(TrapUnreachable))' to panic"
   1: "contract call invocation resulted in error Status(VmError(TrapUnreachable))"
   2: "caught panic from contract function 'Symbol(add_with)', propagating escalated error 'Status(VmError(TrapUnreachable))'"
   3: "escalating error 'Status(VmError(TrapUnreachable))' to panic"
   4: "contract call invocation resulted in error Status(VmError(TrapUnreachable))"
   5: "TrapUnreachable"

Backtrace (newest first):
   0: soroban_env_host::host::err_helper::<impl soroban_env_host::host::Host>::err
             at /home/graydon/.cargo/git/checkouts/rs-soroban-env-230c62c6b1f3d3f1/993c527/soroban-env-host/src/host/err_helper.rs:18:37
   1: soroban_env_host::host::err_helper::<impl soroban_env_host::host::Host>::err_status_msg
             at /home/graydon/.cargo/git/checkouts/rs-soroban-env-230c62c6b1f3d3f1/993c527/soroban-env-host/src/host/err_helper.rs:43:9
   2: <soroban_env_host::host::Host as soroban_env_common::vmcaller_checked_env::VmCallerCheckedEnv>::escalate_error_to_panic
             at /home/graydon/.cargo/git/checkouts/rs-soroban-env-230c62c6b1f3d3f1/993c527/soroban-env-host/src/host.rs:1191:26
   3: soroban_env_common::vmcaller_checked_env::<impl soroban_env_common::checked_env::CheckedEnv for T>::escalate_error_to_panic
             at /home/graydon/.cargo/git/checkouts/rs-soroban-env-230c62c6b1f3d3f1/993c527/soroban-env-common/src/vmcaller_checked_env.rs:210:17
   4: soroban_env_common::checked_env::<impl soroban_env_common::env::Env for T>::call
             at /home/graydon/.cargo/git/checkouts/rs-soroban-env-230c62c6b1f3d3f1/993c527/soroban-env-common/src/checked_env.rs:126:27
   5: <soroban_sdk::env::Env as soroban_env_common::env::Env>::call
             at /home/graydon/.cargo/git/checkouts/rs-soroban-sdk-0ab58a716c671239/e1c3de3/soroban-sdk/src/env.rs:774:13
   6: soroban_sdk::env::Env::invoke_contract
             at /home/graydon/.cargo/git/checkouts/rs-soroban-sdk-0ab58a716c671239/e1c3de3/soroban-sdk/src/env.rs:268:18
   7: soroban_cross_contract_b_contract::ContractBClient::add_with::{{closure}}
             at src/lib.rs:13:1
   8: soroban_cross_contract_b_contract::ContractBClient::with_env
             at src/lib.rs:13:1
   9: soroban_cross_contract_b_contract::ContractBClient::add_with
             at src/lib.rs:13:1
  10: soroban_cross_contract_b_contract::test::test
             at src/test.rs:20:15
  11: soroban_cross_contract_b_contract::test::test::{{closure}}
             at src/test.rs:7:11
  12: core::ops::function::FnOnce::call_once
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/ops/function.rs:507:5

', /home/graydon/.cargo/git/checkouts/rs-soroban-env-230c62c6b1f3d3f1/993c527/soroban-env-host/src/host.rs:1192:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

Is this better-enough? I'm not sure how to act on this bug besides "always make things better" which is a kinda forever-issue.

**Comment by graydon** [comment]
ping @leighmcculloch
